
# Required to work with alethea but not needed for building it
required = ["github.com/golang/mock/mockgen"]

# Constraints

[[constraint]]
  name = "github.com/apex/log"
  version = ">=1.0.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = ">=1.6.1"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = ">=6.7.1"

  [[constraint]]
    name = "github.com/satori/go.uuid"
    revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"

  [[constraint]]
    name = "github.com/golang/mock"
    branch = "master"

# Meta

[metadata.heroku]
  root-package = "github.com/q231950/alethea"
  go-version = "1.9"
  install = [ "./..." ]
