# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
      - image: circleci/postgres:9.4

    working_directory: /go/src/github.com/q231950/alethea
    steps:
      - checkout

      - run: go get -v github.com/golang/dep
      - run: ls ${GOPATH}/src
      - run: ls ${GOPATH}/bin
      - run: ${GOPATH}/bin/dep ensure
      - run: go test -v ./...
